### ISSUE TITLE
Instructions to connect to a Raspberry from another PC

### ISSUE THREAD

**Issue by francofusco** [francofusco/pendule_pi#18]
@Agachon06 you said you were able to connect to your RPi over WiFi, isn't it? Can you tell me how you did it or write it down in the documentation? (You can edit the page `doc/extra/tutorials/multi_machine.md`). I can write down some instructions to set up a new wired connection, but I think it wouldn't be the ideal way of doing it :confused:

**Comment by Agachon06** [comment]
@francofusco, I did it using raspi-config. Fast and easy.
I will try to do it also with command line and I will add it in the documentation :-)

**Comment by francofusco** [comment]
Ok, thanks! I'll try to do it as well on my personal RPi and take screenshots of the procedure so we can add it to the docs 😊 if you find the way to do it on a cmd line it's just great 👍🏻 is there any official documentation for the procedure? Or did you follow some exotic tutorial / managed by yourself?

**Comment by francofusco** [comment]
Since the configuration depends on the way the local network is configured, I think it better not to give specific instructions. Closing!
