### ISSUE TITLE
test-switches shows that it's always at rest

### ISSUE THREAD

**Issue by ss555** [francofusco/pendule_pi#22]
configuration
`sudo ./pendule_pi_assistant test-switches ../pendule_pi_config.yaml`
doesn't work, while:
`sudo ./pendule_pi_assistant measure-rail ../pendule_pi_config.yaml 30`
tells us that the switch functions perfectly, motor changes the direction when switch is pressed

**Comment by francofusco** [comment]
The culprit: [`atRestCached()`](https://github.com/francofusco/pendule_pi/blob/6a6f88bbbb6ee12acdc37ecf5ccdcf35b0fd8ccd/src/pendule_pi/switch.cpp#L73). It should `return at_rest_now_`.

**Comment by francofusco** [comment]
Solved by #23, closing!
